on:
  pull_request:
    types: [opened, synchronize]
    branches: [ "main" ]

jobs:
  start-check:
    runs-on: ubuntu-22.04
    permissions:
      checks: write   # Permission to create a Check Run
      contents: write # Permission to write a repository_dispatch requests
    steps:
      - name: Create Check
        id: checkrun
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          CHECKID=$(gh api -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f name='Trivy Check' \
            -f head_sha='${{ github.event.pull_request.head.sha }}' \
            -f status='queued' \
            -f 'output[title]=Launching quality gate' \
            -f 'output[summary]=Workflow is launching quality gate.' \
            -f 'output[text]=Please wait for workflow to complete scan.' \
            --jq '.id' \
            /repos/${{ github.repository }}/check-runs)
          echo "checkId=$CHECKID" >> $GITHUB_OUTPUT

      - name: Dispatch quality gate workflow
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f 'event_type=my-check' \
            -f 'client_payload[checkRunId]=${{ steps.checkrun.outputs.checkId }}' \
            -f 'client_payload[sha]=${{ github.sha }}' \
            /repos/${{ github.repository }}/dispatches

    
