on:
  push:

jobs:
  Dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4 
      
    - name: Check Dependencies
      uses: mawosoft/dotnet-dependency-alert@v1
      with:
        token: ${{ secrets.CR_PAT }}
