on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_vulnerabilities:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - run: chmod +x check-vulnerable.sh
      
    - name: Check vulnerabilities
      run: ./check-vulnerable.sh
    
