on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Check_Trivy:
    runs-on: ubuntu-22.04
    steps:
    - name: Install dependencies
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.60.0
        pip install jtbl
      
    - name: Checkout source
      uses: actions/checkout@v4

    - run: chmod +x trivy-scan.sh
      
    - name: Run Trivy script
      run: ./trivy-scan.sh
    
