on:
  pull_request:
    types: [opened, synchronize]
    branches: [ "main" ]

jobs:
  start-check:
    runs-on: ubuntu-22.04
    permissions:
      checks: write   # Permission to create a Check Run
      contents: write # Permission to write a repository_dispatch requests
    steps:
      - name: Create Check
        id: checkrun                    # An ID to allow the step to be referenced
        env:
          GH_TOKEN: ${{ github.token }} # Expose the token for GH CLI
        run: |
          ##########################################################
          # Create a Check Run and indicate that it is being queued
          # Use --jq to return the ID
          ##########################################################

          CHECKID=$(gh api -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f name='Super Check' \
            -f head_sha='${{ github.event.pull_request.head.sha }}' \
            -f status='queued' \
            -f 'output[title]=My Check Run Title' \
            -f 'output[summary]=A *fancy* summary' \
            -f 'output[text]=More detailed Markdown **text**' \
            --jq '.id' \
            /repos/${{ github.repository }}/check-runs)
          
          ####################################################
          # Put the ID into a step variable
          ####################################################

          echo "checkId=$CHECKID" >> $GITHUB_OUTPUT

      - name: Repository Dispatch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ##########################################################
          # Create a repository_dispatch event of type my-check
          # Send the SHA and the Check Run ID in the client_payload
          ##########################################################

          gh api -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f 'event_type=my-check' \
            -f 'client_payload[checkRunId]=${{ steps.checkrun.outputs.checkId }}' \
            -f 'client_payload[sha]=${{ github.sha }}' \
            /repos/${{ github.repository }}/dispatches

  Check_Trivy:
    runs-on: ubuntu-22.04
    steps:
    - name: Install dependencies
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.60.0
        pip install jtbl
      
    - name: Checkout source
      uses: actions/checkout@v4

    - run: chmod +x trivy-scan.sh
      
    - name: Run Trivy script
      run: ./trivy-scan.sh
    
